### ISSUE TITLE
[bungee] sync event fires between platforms

### ISSUE THREAD

**Issue by jehendeoff** [Syrent/SayanVanish#324]
Hi again, I created a very simple test plugin to listen to sayan vanish's event (on bungeecord), but I can't manage to get it to fire, is that normal or just misconfiguration ?
here's the (bungeecord) class where the event happens (I did `getProxy().getPluginManager().registerListener(this, new VanishEvent());`)
VanishEvent.class
```java
public class VanishEvent implements Listener {
    public VanishEvent(){
    }

    @EventHandler
    private void onBungeeUserVanishEvent(BungeeUserVanishEvent event) {
        System.out.println("VANISH"); //never seen on bungeecord's console
    }
    @EventHandler
    private void onBungeeUserUnVanishEvent(BungeeUserUnVanishEvent event) {
        System.out.println("UNVANISH"); //never seen on bungeecord's console either
    }
}
```

I have configured mysql and redis on my backend (paper) and front-end (bungeecord)
database.yml
```yaml
method: SQL
sql:
    method: MYSQL
    host: 192.168.0.100
    port: 3306
    database: sayanvanish
    username: sayanvanish
    password: REDACTED
    pool-properties:
        maximum-pool-size: 10
        minimum-idle: 10
        maximum-lifetime: 1800000
        keepalive-time: 0
        connection-timeout: 5000
        use-ssl: false
        verify-server-certificate: false
        allow-public-key-retrieval: true
    table-prefix: sayanvanish_
redis:
    type: STANDALONE
    standalone:
        host: 192.168.0.100
        port: 6379
        user: ''
        password: ''
        ssl: false
use-cache-when-available: true
```
and activated proxy mode in settings.yml

I have no errors in mariadb, redis, bungeecord and paper. I think that the bungeecord plugin isn't communicating with the paper one, I don't know how they should (redis ? plugin message ? mysql ?), nor how to debug this.

if you want me to run some debugging step, I'll be happy to do so
