### ISSUE TITLE
Visual bug tablist

### ISSUE THREAD

**Issue by JuraRusan** [Syrent/SayanVanish#336]
Additionally, during the same [discussion](https://github.com/Syrent/SayanVanish/issues/335) in Discord with the Velocitab plugin developers, a visual bug was noticed. 

Is this a bug, or could it be due to my incorrect configuration?

- video - https://youtu.be/2KWNCTxmZ3k
- console warn
![image](https://github.com/user-attachments/assets/c26330eb-5bd5-4641-bc2a-41aae86a21d2)

The developer of the Velocitab plugin suggested joining the discussion in Discord to help identify the issue. 
- [discord invite](https://discord.gg/tVYhJfyDWG)
- [message discussion](https://discord.com/channels/818135932103557162/1154506106748551309/1276294162768986193)

Thanks in advance!

**Comment by Syrent** [comment]
disable `prevent_push` feature

**Comment by JuraRusan** [comment]
I disabled this flag, but it’s still happening. Additionally, I noticed that when the administrator is in spectator mode, they start rapidly falling through the map.

Right now, I plan to thoroughly review all the configuration files and test everything again.

I'll write a little later

**Comment by JuraRusan** [comment]
[HuskSync](https://www.spigotmc.org/resources/husksync-1-17-1-21-sync-inventories-e-chests-x-server-advancements-map-art-stats-backups.97144/) is used for connecting servers (GMGame, FarmWorld, ResourcesWorld), so modes transfer across them.

**Comment by Syrent** [comment]
I tried to disable `prevent_push` feature and it seems to fix the warning.

https://github.com/user-attachments/assets/3201e794-1839-4f7f-ad35-f27932cb2575


my `/sayanvanish paste` data:
https://paste.sayandev.org/mN9PMkxyNA

try this snapshot for problems in the video:
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.5.0-SNAPSHOT-build.185

**Comment by JuraRusan** [comment]
Oh, you have a cool feature for providing information about the plugin settings. (I only changed my IP since these aren't local servers).

I'm probably doing something wrong, but I can't figure out what it is.

- lobby : https://paste.sayandev.org/k4S8uBjnzj
- res: https://paste.sayandev.org/wXUU0vTEE6

But as I understand it, this feature isn't available on Velocity, so I took the file from the logs folder.
- velocity [latest.log](https://github.com/user-attachments/files/16731560/latest.log)

I suspect the issue might be on my end, but I'm not sure why. If a player is in vanish mode on one server, they remain hidden, but when they switch to another server, they stay in vanish mode but are no longer hidden in the tab list. And in spectator mode, they just fall through the map. It's quite amusing.

Sorry if I'm bothering you with this bug. But I don’t know what to do.

**Comment by Syrent** [comment]
I'm happy to help with SayanVanish! If you run into any other issues or have more questions, feel free to ask.
I was able to replicate the problem on my local server and made some adjustments to the code. Please try this updated build, it should address the issue you mentioned.
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.5.0-SNAPSHOT-build.186

**Comment by JuraRusan** [comment]
Unfortunately, I will only be able to check in 1 day, or if possible only in the evening.

**Comment by Syrent** [comment]
No problem! I'm currently updating SayanVanish. Before you start testing, be sure to check Hangar to see if I've released a new snapshot.
https://hangar.papermc.io/Syrent/SayanVanish/versions

**Comment by JuraRusan** [comment]
So, I conducted testing and finally found the cause of this bug!!!
Now, I’ll document everything and prepare the logs. This will take some time.

**Comment by JuraRusan** [comment]
I set up local servers and proxies so that I wouldn't have to edit and re-save files later, but send everything as is..

Video - https://youtu.be/7pDgoTa8r1Y (_Sorry the video is too long but I had to show everything in the queue._)

Velocitab main config - https://paste.sayandev.org/bYJIft9B3G (the file was used all 3 times, it was also generated by the plugin, but I replaced only `papi_cache_time: 30000` -> `papi_cache_time: 5000` )

Velocitab noformat - https://paste.sayandev.org/Roh0Xz4dz3 ( my custom file, only <velocitab_rel_condition..s removed )
Velocitab custom - https://paste.sayandev.org/u0bMbxapqM  ( use it on the main server )
Velocitab default - https://paste.sayandev.org/9kFOGwgifp ( generated by the plugin, except for one line where %sayanvanish_online_total% is added )

Lobby - https://paste.sayandev.org/dp5BeIlFHH
FarmWorld - https://paste.sayandev.org/ccPdolWTE3
GMGame - https://paste.sayandev.org/XKp9v3sm0I

Copied from the logs folder, one by one, all 3 files:
Velocity log 1 - https://paste.sayandev.org/bSaWo48zol
Velocity log 2 - https://paste.sayandev.org/c2iN8FjRZZ
Velocity log 3 - https://paste.sayandev.org/mUZEdky50p
 
 
Also, for some reason it is not clear why the commands work only in the lobby, on other servers they do not. I checked the settings, everything is identical. This is really funny..

I also noticed that the character falls through the map and dies, although the items remain in place.
Video - https://youtu.be/KCGriHdJV5M


I hope I didn't throw in too much..

**Comment by Syrent** [comment]
The issue with spectators falling and the commands can be easily resolved. For now, let's concentrate on the tab problems.

From what I gathered from the video, the plugin works correctly with the default configuration and with custom configurations that don't use relative placeholders. If that's the case, I'm unsure why you're using relative placeholders, I'm not entirely familiar with how those work in Velocitab. It seems like this might be an issue with Velocitab itself, right?

**Comment by Syrent** [comment]
you need `sayanvanish.action.vanish.fly.keep_after_reappear` to keep fly status after unvanish. let me know if it solves the problem.
about the command issue i need to try a few things.

**Comment by Syrent** [comment]
the command problem could easily be a permission problem. make sure you have the right permissions to use commands.
main permission for root command: `sayanvanish.commands.use`
other commands: `sayanvanish.commands.<literal>` (e.g: `sayanvanish.commands.forceupdate` or `sayanvanish.command.feature.toggleplayer`)

**Comment by JuraRusan** [comment]
I had LuckPerms connected via proxy and MySQL, and I gave myself `sayanvanish.commands.use` on all servers, but for some reason it didn't work on the test server, and I still don't understand why. Most likely my stupidity. So I gave up and decided to just move everything to the main server, and everything worked.

**Comment by JuraRusan** [comment]
I basically got rid of custom fillers and use almost vanilla settings.
But I noticed one oddity. I want to spend more time studying it. I'll write later.

**Comment by JuraRusan** [comment]
So, for some reason, I don’t understand anything...

All this time, I’ve been trying to solve one problem, but in the process, I encountered others. We have almost identical plugins installed on four servers. For two days now, I’ve been comparing them using https://charactercalculator.com/ru/text-compare/, and there’s no difference. But for some reason, one of the four servers is throwing the following error:
```log
[16:54:35 INFO]: [connected player] prestig9110 (<ip address withheld>) has connected
[16:54:36 INFO] [velocitab]: Failed to un-vanish player prestig9110 as they are not in the tab list
[16:54:36 INFO]: [server connection] prestig9110 -> ResourcesWorld has connected
[16:54:36 INFO] [velocitab]: Failed to un-vanish player prestig9110 as they are not in the tab list
[16:54:36 INFO] [velocitab]: Failed to un-vanish player prestig9110 as they are not in the tab list
[16:54:36 INFO] [nlogin]: The user prestig9110 logged in automatically (premium account)
[16:54:36 WARN] [velocitab]: Cancelled team "Vanished" packet from backend for player prestig9110. We suggest disabling "send_scoreboard_packets" in Velocitab's config.yml file, but note this will disable TAB sorting
```
I fully understand that this is an error or warning from Velocitab, not from the SayanVanish plugin, and it occurs for all players. But the error:
```log
[velocitab]: Failed to un-vanish player prestig9110 as they are not in the tab list
```
appears for all players, regardless of which server they connect to.

I started investigating, and considering that I have the CMI plugin installed on all four servers, I disabled the DisableTeamManagement: true function on all servers a long time ago to get rid of the team packet.

And while I was trying to figure out why the `Cancelled team "Vanished" packet from backend...` error is occurring exclusively on one server, I noticed that when an administrator is in vanish, and any player joins the server, they can see the administrator, even though they’re supposed to be hidden. But if the administrator switches servers, they disappear again for the player. And sometimes, `<sayanvanish_online_total>` updates strangely, in one video, it’s immediately visible as 9, then when switching, it’s 10, and then back to 9. Tomorrow, when the server reboots, the update time will no longer be `papi_cache_time: 5000`ms but `papi_cache_time: 1000`ms. Maybe this will help?..

https://youtu.be/JG85FPlRp6M

All servers have identical [features](https://paste.sayandev.org/WLkMmZuZDR); I simply copied the folder to all servers. Similarly, `database.yml` was copied, but `settings.yml` was generated automatically by the plugin. I manually configured `proxy-mode: true`.

I use version:
- Velocity: `SayanVanish-1.5.0-SNAPSHOT-build.189-99bb76a-proxy-velocity.jar`
- Paper: `SayanVanish-1.5.0-SNAPSHOT-build.189-99bb76a-bukkit.jar`

- `Velocitab-1.7-5ae3229.jar` (Tomorrow when the server is rebooted there will already be a version `Velocitab-1.7.1.jar`)

I'm already somewhat desperate. I created the configurations from scratch, double-checked everything, but for some reason, this funny issue keeps happening. I've been dealing with this for days, and there's no end in sight.

Sorry if I'm writing too much; I just want to do everything right. If this is my mistake, I'll keep trying to figure it out and find the solution. But if it's a bug, could you please help?

**Comment by JuraRusan** [comment]
Tomorrow we’ll see after the reboot how things will be after updating the plugin version and reducing the synchronization time.

**Comment by Syrent** [comment]
Hi, I discovered an issue where the plugin wasn’t correctly saving the online status of vanished users, which prevented it from loading all of them. Try using this version instead:
https://hangar.papermc.io/Syrent/SayanVanish/versions/1.5.0-SNAPSHOT-build.190

**Comment by JuraRusan** [comment]
Thank you! I'll check after rebooting the servers!

**Comment by JuraRusan** [comment]
Thank you very much, and I apologize for the delay in responding. 

I managed to upload and test the fix—the error `[velocitab]: Failed to un-vanish player prestig9110 as they are not in the tab list` has indeed disappeared, and the console is now clean. However, the problem with tabs when switching servers remains: players who disappeared continue to be displayed when changing servers. This is likely not related to your part anymore. The Velocitab developer promised to look into it in a week or two, so for now, we can only wait.

**Comment by JuraRusan** [comment]
A little more than 2 weeks have passed. The result is this ... 
![image](https://github.com/user-attachments/assets/2aae04b7-068b-4b90-854e-e70697457991)

**Comment by Syrent** [comment]
I'm not able to fully remember the exact cause of the issue, but I believe it was related to a change in the configuration. Could you remind me what was changed? I can test the configuration that triggers the problem on my side and try to debug it. That way, I might be able to figure out why the issue occurs.

**Comment by JuraRusan** [comment]
Right now I'm using this configuration, I checked it 10 minutes ago, the problem is reproducible.

- video I provided to the Velocitab developers https://youtu.be/U7fzlftK4qw
- Velocitab config: 
```yml
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃      Velocitab TabGroups     ┃
# ┃    Developed by William278   ┃
# ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# ┣╸ Information: https://william278.net/project/velocitab
# ┗╸ Documentation: https://william278.net/docs/velocitab

groups:
- name: default
  headers:
  - |-
    <#caeaf5>
    <#caeaf5>    Добро пожаловать <#55ff55>%username%    <#caeaf5>
    <#caeaf5>Онлайн: <#55ff55>%sayanvanish_online_total%
    <#caeaf5>
  footers:
  - |-
    <#caeaf5>
    <#caeaf5>Сервер: <#55ff55>%server%
    <#caeaf5>    Пинг: <#55ff55>%ping% <#caeaf5>TPS: <#55ff55>%server_tps_1% <#caeaf5>GMCoin: <#55ff55>%coinsengine_balance_plain_gmcoin%    <#55ff55>
    <#caeaf5>
  format: <gray>[<#00fa9a><velocitab_rel_condition:"%server%" == 'Lobby':Lobby:><#fa8072><velocitab_rel_condition:"%server%" == 'Event':Event:><#f6c25d><velocitab_rel_condition:"%server%" == 'GMGame':GMGame:><#83f28f><velocitab_rel_condition:"%server%" == 'CreativeWorld':CreativeWorld:><#ffb6c1><velocitab_rel_condition:"%server%" == 'FarmWorld':FarmWorld:><#6495ed><velocitab_rel_condition:"%server%" == 'ResourcesWorld':ResourcesWorld:><gray>] <#caeaf5>%javascript_afk_players%%username%%javascript_world_hex%   <#caeaf5>
  nametag:
    prefix: <#ffffff>
    suffix: <#ffffff>
  servers:
  - FarmWorld
  - Lobby
  - Event
  - CreativeWorld
  - GMGame
  - ResourcesWorld
  sorting_placeholders:
  - '%server%'
  - '%username_lower%'
  collisions: false
  header_footer_update_rate: 1000
  placeholder_update_rate: 1000
  only_list_players_in_same_server: false
```

- `Velocitab-1.7.1-852c3e8-indev.jar`
- `SayanVanish-1.5.0-SNAPSHOT-build.190-998b381-proxy-velocity.jar`
- https://paste.sayandev.org/dQwWkvhAli

If you need more detailed information, I can provide it later. Just tell me what is missing from the files.
